# Generated by Django 4.2.2 on 2023-06-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(help_text="Nome do game", max_length=250)),
                (
                    "plataforma",
                    models.CharField(help_text="Plataforma", max_length=100),
                ),
                ("finalizado", models.BooleanField(help_text="Finalizado?")),
                ("data_criado", models.DateTimeField(auto_now_add=True)),
                ("data_alterado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "db_table": "game",
                "ordering": ["-id"],
            },
        ),
    ]
