# Generated by Django 5.0.6 on 2024-06-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plataforma",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da plataforma. Ex: Playstation 2",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plataforma",
                "verbose_name_plural": "Plataformas",
                "db_table": "plataforma",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(help_text="Nome do game", max_length=250)),
                ("finalizado", models.BooleanField(help_text="Finalizado?")),
                (
                    "completado",
                    models.BooleanField(
                        help_text="Verdadeiro caso tenha obtido o set completo de conquistas/trofeus"
                    ),
                ),
                (
                    "midia",
                    models.CharField(
                        choices=[("FISICA", "Física"), ("DIGITAL", "Digital")],
                        help_text="Tipo de mídia. Ex: física, digital",
                        max_length=10,
                    ),
                ),
                ("data_criado", models.DateTimeField(auto_now_add=True)),
                ("data_alterado", models.DateTimeField(auto_now=True)),
                (
                    "plataforma",
                    models.ForeignKey(
                        help_text="Plataforma",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plataforma",
                        to="games.plataforma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "db_table": "game",
                "ordering": ["nome", "plataforma"],
            },
        ),
    ]
