# Generated by Django 5.0.6 on 2024-06-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="plataforma",
            field=models.ForeignKey(
                help_text="Plataforma",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                related_query_name="game",
                to="games.plataforma",
            ),
        ),
    ]
