# Generated by Django 5.1.4 on 2025-01-03 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_add_game_lista_desejos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Progresso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("finalizado", models.BooleanField(help_text="Finalizado?")),
                (
                    "completado",
                    models.BooleanField(
                        help_text="Verdadeiro caso tenha obtido o set completo de conquistas/trofeus"
                    ),
                ),
                ("lista_desejos", models.BooleanField(help_text="Lista de desejos?")),
                ("data_criado", models.DateTimeField(auto_now_add=True)),
                ("data_alterado", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_progresso",
                        related_query_name="game_progresso",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_game_progresso",
                        related_query_name="user_game_progresso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso",
                "verbose_name_plural": "Progressos",
                "db_table": "progresso",
                "ordering": ["game"],
            },
        ),
    ]
