# Generated by Django 5.1.4 on 2025-01-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_add_progresso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="completado",
        ),
        migrations.RemoveField(
            model_name="game",
            name="finalizado",
        ),
        migrations.RemoveField(
            model_name="game",
            name="lista_desejos",
        ),
    ]
