# Generated by Django 5.1.5 on 2025-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "games",
            "0001_initial_squashed_0005_remove_game_completado_remove_game_finalizado_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("nome", "plataforma_id"),
                name="unique_game_plataforma",
                violation_error_message="Game deve ser único por plataforma",
            ),
        ),
    ]
